[package]
name = "rust_programming_language"
version = "0.1.0"
authors = ["MonchiLin <lin912305043@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rand = "0.7.3"
